export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import Navbar from './components/navbar'
import Chatbot from './components/chatbot';
import { getCities } from './modules/remoteServices';

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const cities = await getCities();

  //list of cities passed to navbar
  return (
    <html lang="en">

      <body className='bg-violet-50  flex flex-col min-h-screen'>
        <Navbar CitiesObj={cities}></Navbar>
        <main className="flex-grow">
          {children}
          <Chatbot></Chatbot>
          </main>
        <footer className='content h-8 text-center bg-indigo-600 text-white mt-6'>
          <p>© 2025 davidk</p>
          
        </footer>
      </body>
    </html>
  )
}
